export interface Skill {
  id: string;
  emoji: string;
  name: string;
  time: string;
  description: string;
  xp: number;
  howTo: string[];
  bio: string[];
  tags: string[];
}

export interface Dimension {
  id: number;
  key: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
  skills: Skill[];
}

export const DIMENSIONS: Dimension[] = [
  {
    id: 0,
    key: 'biologie',
    name: 'Biologie',
    emoji: '🫀',
    color: '#FF6B7A',
    description: 'Körperliche Gesundheit, Bewegung, Schlaf & Ernährung',
    skills: [
      {
        id: 'bio_1',
        emoji: '🚶',
        name: '10 Min Spaziergang',
        time: '10 Min',
        description: 'Moderate Bewegung aktiviert das Herz-Kreislauf-System und fördert die Blutversorgung des Präfrontalkortex.',
        xp: 15,
        howTo: [
          'Aufrecht stehen, Schultern entspannt',
          'Natürliche Schritte, nicht zu groß',
          'Arme schwingen natürlich',
          'Gleichmäßiges, moderates Tempo',
          'Rhythmisch atmen: Nase ein, Mund aus',
        ],
        bio: ['❤️ Herzrate → 100-120 BPM', '🧠 Gehirn-Blutfluss +40%', '🔬 BDNF-Ausschüttung nach 8 Min'],
        tags: ['bewegung', 'draußen', 'anfänger'],
      },
      {
        id: 'bio_2',
        emoji: '🏃',
        name: 'HIIT Micro-Session',
        time: '5 Min',
        description: 'Hochintensives Intervalltraining (20 Sek Arbeit, 10 Sek Pause) maximiert mitochondriale Effizienz.',
        xp: 25,
        howTo: [
          '30 Sek aufwärmen mit leichter Bewegung',
          '20 Sekunden Sprint / Hochintensiv',
          '10 Sekunden aktive Pause (gehen)',
          'Zyklus 10x wiederholen (5 Minuten)',
          'Cool-down mit tiefer Atmung',
        ],
        bio: ['⚡ Mitochondriale Biogenese aktiviert', '🔥 Stoffwechsel 24h erhöht', '💪 Schnellzuckerfasern rekrutiert'],
        tags: ['bewegung', 'intensiv', 'schnell'],
      },
      {
        id: 'bio_3',
        emoji: '🧘',
        name: 'Yoga Flow',
        time: '15 Min',
        description: 'Dynamische Bewegungssequenzen verbinden Atem und Bewegung, fördern Flexibilität.',
        xp: 20,
        howTo: [
          'Mit Erdungspose beginnen (Berg/Kind)',
          'Sonnengrüße durchführen (3-5 Runden)',
          'Balance-Posen einbauen (Baum, Krieger)',
          'Atem mit jeder Bewegung synchronisieren',
          'Mit Savasana abschließen (2-3 Min)',
        ],
        bio: ['🧘 Kortisol & Entzündungsmarker gesenkt', '🫁 Lungenkapazität erhöht', '🧠 Geist-Körper-Verbindung gestärkt'],
        tags: ['bewegung', 'entspannung', 'flexibilität'],
      },
      {
        id: 'bio_4',
        emoji: '😴',
        name: 'Schlaf-Ritual',
        time: '20 Min',
        description: 'Konsequentes Abend-Ritual signalisiert dem Körper den Übergang in die Erholung.',
        xp: 20,
        howTo: [
          'Bildschirme 30 Min vor Schlaf ausschalten',
          'Dimmes Licht oder Kerzen verwenden',
          'Gleiche Schlafenszeit einhalten',
          '4-7-8 Atemtechnik: 4 ein, 7 halten, 8 aus',
          'Temperatur auf ~18°C einstellen',
        ],
        bio: ['🌙 Melatonin-Produktion gefördert', '🧠 Glymphatisches System aktiviert', '💪 HGH-Ausschüttung optimiert'],
        tags: ['schlaf', 'erholung', 'abend'],
      },
      {
        id: 'bio_5',
        emoji: '🥗',
        name: 'Nährstoff-Boost',
        time: '5 Min',
        description: 'Gezielte Aufnahme von Mikronährstoffen unterstützt Gehirnfunktion und Zellreparatur.',
        xp: 10,
        howTo: [
          'Wasser als erstes beim Aufwachen trinken',
          'Proteinreiche Mahlzeit wählen',
          'Bunte Gemüsevielfalt einbauen',
          'Omega-3 Quellen: Lachs, Walnüsse, Leinsamen',
          'Zucker & verarbeitete Lebensmittel reduzieren',
        ],
        bio: ['🧠 Neurotransmitter-Vorstufen geliefert', '🔋 Mitochondriale Energie erhöht', '🛡️ Entzündungen reduziert'],
        tags: ['ernährung', 'energie', 'fokus'],
      },
    ],
  },
  {
    id: 1,
    key: 'emotion',
    name: 'Emotion',
    emoji: '🎭',
    color: '#F5A623',
    description: 'Emotionale Intelligenz, Regulation & innere Balance',
    skills: [
      {
        id: 'emo_1',
        emoji: '🔮',
        name: 'Klarheits-Atemübung',
        time: '5 Min',
        description: 'Box Breathing aktiviert das parasympathische Nervensystem und reduziert Stresshormone.',
        xp: 15,
        howTo: [
          'Bequem sitzen, Augen schließen',
          '4 Sek einatmen durch Nase',
          '4 Sek Atem anhalten',
          '4 Sek ausatmen durch Mund',
          '4 Sek Pause. 4-6x wiederholen.',
        ],
        bio: ['🧘 Kortisol in 5 Min um 23% gesenkt', '❤️ HRV & Vagusnerv-Tonus erhöht', '🧠 Amygdala-Reaktivität gedämpft'],
        tags: ['stress', 'atmung', 'anfänger'],
      },
      {
        id: 'emo_2',
        emoji: '📓',
        name: 'Gefühls-Tagebuch',
        time: '10 Min',
        description: 'Detaillierte Aufzeichnung emotionaler Episoden fördert Selbst-Awareness und Mustererkennung.',
        xp: 18,
        howTo: [
          'Auslösende Situation beschreiben',
          'Alle Gefühle benennen',
          'Intensität bewerten (1-10)',
          'Körperliche Empfindungen notieren',
          'Muster über Zeit identifizieren',
        ],
        bio: ['🧠 Selbst-Awareness vertieft', '📊 Muster-Erkennung verbessert', '😌 Emotionale Intelligenz erhöht'],
        tags: ['tagebuch', 'reflexion', 'muster'],
      },
      {
        id: 'emo_3',
        emoji: '🌊',
        name: 'Gefühle benennen',
        time: '3 Min',
        description: 'Affect Labeling: Emotionen zu benennen reduziert ihre neurobiologische Intensität.',
        xp: 10,
        howTo: [
          'Innehalten und nach innen schauen',
          'Welche Emotion spüre ich gerade?',
          'So präzise wie möglich benennen',
          '"Ich fühle ___" (nicht "Ich bin ___")',
          'Beobachten wie Intensität sinkt',
        ],
        bio: ['🧠 Präfrontale Hemmung der Amygdala', '😌 Emotionale Reaktivität -50%', '💡 Selbst-Regulation verbessert'],
        tags: ['achtsamkeit', 'regulation', 'schnell'],
      },
      {
        id: 'emo_4',
        emoji: '🙏',
        name: 'Dankbarkeits-Praxis',
        time: '5 Min',
        description: '3 echte Dinge aufschreiben, für die du dankbar bist. Rewiriert neuronale Negativitäts-Bias.',
        xp: 12,
        howTo: [
          '3 spezifische Dinge aufschreiben',
          'Nicht allgemein: Sei konkret',
          'Warum ist es bedeutsam?',
          'Körperliche Empfindung erspüren',
          'Tägliche Praxis zur gleichen Zeit',
        ],
        bio: ['😊 Dopamin-Belohnungssystem aktiviert', '🧠 Negativitäts-Bias reduziert', '❤️ Soziale Bindungshormone erhöht'],
        tags: ['dankbarkeit', 'positiv', 'täglich'],
      },
      {
        id: 'emo_5',
        emoji: '🎵',
        name: 'Musik & Gefühl',
        time: '10 Min',
        description: 'Musik gezielt für Stimmungsregulation einsetzen — eines der wirksamsten emotionalen Tools.',
        xp: 12,
        howTo: [
          'Aktuelle Stimmung erkennen',
          'Passende Playlist wählen',
          'Bewusst hören, nicht nebenbei',
          'Körperliche Resonanz zulassen',
          'Stimmungsveränderung beobachten',
        ],
        bio: ['🎵 Dopamin-Ausschüttung erhöht', '🧠 Limbisches System reguliert', '❤️ Herzrate synchronisiert'],
        tags: ['musik', 'stimmung', 'genuss'],
      },
    ],
  },
  {
    id: 2,
    key: 'sozial',
    name: 'Sozial',
    emoji: '🤝',
    color: '#60A5FA',
    description: 'Verbindungen, Beziehungen & soziale Kompetenz',
    skills: [
      {
        id: 'soc_1',
        emoji: '💬',
        name: 'Jemanden anrufen',
        time: '15 Min',
        description: 'Synchrone Kommunikation aktiviert soziale Kognitionsnetzwerke und fördert Bindungsmechanismen.',
        xp: 20,
        howTo: [
          'Person wählen, die dir wichtig ist',
          'Anrufen (nicht texten)',
          'Fragen wie es wirklich geht',
          'Aktiv zuhören ohne unterbrechen',
          'Authentisch selbst teilen',
        ],
        bio: ['🤗 Oxytocin-Freisetzung (Bindung)', '😊 Einsamkeit reduziert', '🧠 Soziale Gehirn-Netzwerke aktiviert'],
        tags: ['verbindung', 'gespräch', 'freundschaft'],
      },
      {
        id: 'soc_2',
        emoji: '🤝',
        name: 'Kompliment geben',
        time: '2 Min',
        description: 'Prosoziales Verhalten aktiviert Belohnungszentren und stärkt soziale Bindungen.',
        xp: 10,
        howTo: [
          'Etwas Echtes bemerken zu schätzen',
          'Spezifisch sein (nicht generisch)',
          'Augenkontakt machen',
          'Aufrichtig ohne Erwartung',
          'Ihre Reaktion warm wahrnehmen',
        ],
        bio: ['😊 Dopamin-Belohnung aktiviert', '🤗 Soziale Bindungen gestärkt', '❤️ Positive Reziprozität initiiert'],
        tags: ['positiv', 'schnell', 'beziehung'],
      },
      {
        id: 'soc_3',
        emoji: '🍽️',
        name: 'Gemeinsam essen',
        time: '30 Min',
        description: 'Geteilte Mahlzeiten synchronisieren soziale Rhythmen und fördern Gruppenkohäsion.',
        xp: 25,
        howTo: [
          'Jemanden zum gemeinsamen Essen einladen',
          'Alle Bildschirme weglegen',
          'Im gleichen Tempo essen',
          'Echtes Gespräch führen',
          'Die geteilte Erfahrung genießen',
        ],
        bio: ['🍽️ Soziale Rhythmen synchronisiert', '🤗 Oxytocin durch Gemeinschaft', '🧠 Soziale Kohäsion gestärkt'],
        tags: ['essen', 'gemeinschaft', 'ritual'],
      },
      {
        id: 'soc_4',
        emoji: '💝',
        name: 'Kleine Geste',
        time: '10 Min',
        description: 'Geschenk, Nachricht oder Aufmerksamkeit für anderen planen.',
        xp: 15,
        howTo: [
          'Denk an jemanden zum Wertschätzen',
          'Überlege was bedeutsam wäre',
          'Erstelle/kaufe/schreibe die Geste',
          'Übergib durchdacht',
          'Keine Erwartung an Gegenleistung',
        ],
        bio: ['😊 Prosoziale Motivation aktiviert', '🤗 Altruismus-Netzwerke engagiert', '❤️ Großzügigkeit verstärkt'],
        tags: ['geste', 'fürsorge', 'verbindung'],
      },
    ],
  },
  {
    id: 3,
    key: 'kognition',
    name: 'Kognition',
    emoji: '🧠',
    color: '#4ECCA3',
    description: 'Mentale Klarheit, Fokus, Lernen & Problemlösung',
    skills: [
      {
        id: 'cog_1',
        emoji: '📚',
        name: '25 Min Lesen',
        time: '25 Min',
        description: 'Tiefes Lesen stärkt neuronale Verbindungen und fördert kritisches Denken.',
        xp: 20,
        howTo: [
          'Ablenkungen minimieren (Stille/Fokus)',
          'Physisches Buch oder E-Reader',
          'Aktiv lesen: Notizen machen',
          'Fragen stellen: Was ist der Kern?',
          'Mit eigenen Worten zusammenfassen',
        ],
        bio: ['📚 Neuronale Verbindungen gestärkt', '🧠 Kritisches Denken gefördert', '💡 Wortschatz & Ideen erweitert'],
        tags: ['lesen', 'lernen', 'konzentration'],
      },
      {
        id: 'cog_2',
        emoji: '🧩',
        name: 'Pomodoro-Session',
        time: '25 Min',
        description: '25 Min fokussierte Arbeit + 5 Min Pause: optimiert Konzentration und verhindert Burnout.',
        xp: 22,
        howTo: [
          'Eine einzige Aufgabe wählen',
          'Timer auf 25 Min stellen',
          'Ablenkungsfrei arbeiten',
          '5 Min Pause nach dem Timer',
          'Nach 4 Runden: 15 Min Pause',
        ],
        bio: ['🎯 Präfrontale Kortex-Kapazität optimiert', '🔋 Mentale Ausdauer aufgebaut', '⚡ Flow-State begünstigt'],
        tags: ['fokus', 'produktivität', 'methode'],
      },
      {
        id: 'cog_3',
        emoji: '✍️',
        name: 'Free Writing',
        time: '10 Min',
        description: 'Unkontrolliertes Schreiben für 10 Min: klärt Gedanken und fördert kreatives Denken.',
        xp: 15,
        howTo: [
          'Timer auf 10 Min stellen',
          'Pen auf Papier, nie aufhören',
          'Keine Kritik, kein Zensieren',
          'Alles schreiben was kommt',
          'Danach lesen und Muster bemerken',
        ],
        bio: ['✍️ Default Mode Network aktiviert', '💡 Kreative Verbindungen gefördert', '🧠 Gedanken-Klarheit erhöht'],
        tags: ['schreiben', 'kreativität', 'klarheit'],
      },
      {
        id: 'cog_4',
        emoji: '🌐',
        name: 'Neues Lernen',
        time: '20 Min',
        description: 'Eine neue Fertigkeit oder ein neues Konzept erlernen aktiviert Neuroplastizität.',
        xp: 25,
        howTo: [
          'Thema wählen das interessiert',
          'Aktive Lernmethode nutzen (nicht nur lesen)',
          'Notizen in eigenen Worten',
          'Anwenden: Erkläre es jemandem',
          'Regelmäßige Wiederholung einplanen',
        ],
        bio: ['🧠 Neuroplastizität aktiviert', '💡 Synaptische Verbindungen gestärkt', '📈 Langzeit-Gedächtnis gefördert'],
        tags: ['lernen', 'neues', 'wachstum'],
      },
    ],
  },
  {
    id: 4,
    key: 'kompetenz',
    name: 'Kompetenz',
    emoji: '🛠️',
    color: '#A78BFA',
    description: 'Fähigkeiten, Leistung & persönliches Wachstum',
    skills: [
      {
        id: 'comp_1',
        emoji: '🎯',
        name: 'Micro-Goal setzen',
        time: '5 Min',
        description: 'Ein kleines, konkret erreichbares Ziel für heute definieren und sofort beginnen.',
        xp: 12,
        howTo: [
          'Großes Ziel in kleinen Schritt zerlegen',
          'Ziel so klein machen, dass Scheitern fast unmöglich',
          'Wann genau wirst du es tun?',
          'Sofort beginnen oder Termin setzen',
          'Abschluss feiern (innerlich)',
        ],
        bio: ['🎯 Dopamin-Vorfreude aktiviert', '💡 Selbstwirksamkeit erhöht', '🔄 Gewohnheitsschleife eingeleitet'],
        tags: ['ziele', 'produktivität', 'anfänger'],
      },
      {
        id: 'comp_2',
        emoji: '🔄',
        name: 'Skill-Praxis',
        time: '30 Min',
        description: 'Bewusstes Üben einer Fertigkeit mit Fokus auf Schwachstellen (Deliberate Practice).',
        xp: 30,
        howTo: [
          'Spezifischen Skill wählen',
          'Schwächste Stelle identifizieren',
          'Nur diese eine Schwäche üben',
          'Sofortiges Feedback suchen',
          'Bis zur Erschöpfung, dann Pause',
        ],
        bio: ['💪 Myelinisierung beschleunigt', '🧠 Motorisches Cortex umstrukturiert', '⚡ Automatisierung aufgebaut'],
        tags: ['üben', 'meisterschaft', 'intensiv'],
      },
      {
        id: 'comp_3',
        emoji: '📊',
        name: 'Fortschritt tracken',
        time: '5 Min',
        description: 'Messbarer Fortschritt sichtbar machen stärkt Motivation und zeigt Entwicklung.',
        xp: 10,
        howTo: [
          'Aktuelle Leistung messen/notieren',
          'Mit Vorwoche vergleichen',
          'Einen Wachstumsmoment identifizieren',
          'Nächsten Meilenstein definieren',
          'Kleiner Fortschritt = Erfolg',
        ],
        bio: ['📊 Fortschritts-Motivation aktiviert', '🎯 Ziel-Commitment gestärkt', '😊 Selbstwirksamkeit erhöht'],
        tags: ['tracking', 'motivation', 'schnell'],
      },
      {
        id: 'comp_4',
        emoji: '🤔',
        name: 'Fehlschlag analysieren',
        time: '10 Min',
        description: 'Misserfolge systematisch analysieren als Lernchance — Growth Mindset in Aktion.',
        xp: 18,
        howTo: [
          'Letzten Fehlschlag neutral beschreiben',
          'Was genau ist schief gelaufen?',
          'Was lag in meiner Kontrolle?',
          'Was würde ich anders machen?',
          'Als Experiment, nicht als Versagen sehen',
        ],
        bio: ['🧠 Growth Mindset neural verankert', '💡 Fehler-Lernschleife aktiviert', '🛡️ Resilienz aufgebaut'],
        tags: ['lernen', 'resilienz', 'reflexion'],
      },
    ],
  },
  {
    id: 5,
    key: 'bedeutung',
    name: 'Bedeutung',
    emoji: '🌟',
    color: '#FF9F43',
    description: 'Sinn, Werte, Purpose & innere Orientierung',
    skills: [
      {
        id: 'mean_1',
        emoji: '🌅',
        name: 'Morgen-Intention',
        time: '5 Min',
        description: 'Tägliche Absichtserklärung ausrichten: Was bedeutet dieser Tag für mich?',
        xp: 12,
        howTo: [
          'Kurz nach dem Aufwachen, still sitzen',
          'Fragen: Was ist mein Sinn heute?',
          'Einen Wert wählen der leiten soll',
          'Eine Absicht formulieren: "Heute werde ich..."',
          'Mit Überzeugung verinnerlichen',
        ],
        bio: ['🌅 Präfrontaler Kortex ausgerichtet', '🎯 Ziel-direktes Verhalten erhöht', '😊 Kohärenzgefühl gestärkt'],
        tags: ['morgen', 'intention', 'sinn'],
      },
      {
        id: 'mean_2',
        emoji: '🌳',
        name: 'Werte-Reflexion',
        time: '10 Min',
        description: 'Eigene Kernwerte bewusst machen und prüfen ob das Handeln ihnen entspricht.',
        xp: 18,
        howTo: [
          'Liste: Was sind meine 5 Kernwerte?',
          'Vergangene Woche reflektieren',
          'Habe ich nach meinen Werten gehandelt?',
          'Wo war eine Lücke?',
          'Einen Wert für diese Woche wählen',
        ],
        bio: ['🌳 Authentizitäts-Netzwerk aktiviert', '🧠 Selbst-Kongruenz erhöht', '❤️ Innere Ruhe gestärkt'],
        tags: ['werte', 'reflexion', 'authentizität'],
      },
      {
        id: 'mean_3',
        emoji: '✨',
        name: 'Ikigai-Moment',
        time: '15 Min',
        description: 'Den eigenen Schnittbereich von Leidenschaft, Talent, Bedürfnis und Beruf erkunden.',
        xp: 22,
        howTo: [
          'Was liebe ich zu tun?',
          'Worin bin ich wirklich gut?',
          'Was braucht die Welt?',
          'Wofür könnte ich bezahlt werden?',
          'Schnittmengen suchen und notieren',
        ],
        bio: ['✨ Purpose-Netzwerk aktiviert', '🌟 Serotonin-Wohlbefinden erhöht', '🧠 Langzeit-Motivation gestärkt'],
        tags: ['sinn', 'purpose', 'tief'],
      },
      {
        id: 'mean_4',
        emoji: '🕯️',
        name: 'Stille & Meditation',
        time: '10 Min',
        description: '10 Min Stille und Präsenz — reduziert mentales Rauschen und stärkt innere Klarheit.',
        xp: 20,
        howTo: [
          'Ruhigen Ort wählen, bequem sitzen',
          'Timer auf 10 Min stellen',
          'Atem als Anker nutzen',
          'Gedanken bemerken ohne festzuhalten',
          'Sanft immer wieder zum Atem zurück',
        ],
        bio: ['🧘 Default Mode Network kalibriert', '🌙 Kortisol nachhaltig gesenkt', '🧠 Selbst-Gewahrsein vertieft'],
        tags: ['meditation', 'stille', 'präsenz'],
      },
    ],
  },
];

// XP levels
export const XP_LEVELS = [
  { level: 1, name: 'Beginner', xpRequired: 0 },
  { level: 2, name: 'Lernender', xpRequired: 100 },
  { level: 3, name: 'Praktizierender', xpRequired: 250 },
  { level: 4, name: 'Fortgeschrittener', xpRequired: 500 },
  { level: 5, name: 'Erfahrener', xpRequired: 1000 },
  { level: 6, name: 'Experte', xpRequired: 2000 },
  { level: 7, name: 'Meister', xpRequired: 4000 },
];

export const getLevelForXP = (xp: number) => {
  let current = XP_LEVELS[0];
  for (const lvl of XP_LEVELS) {
    if (xp >= lvl.xpRequired) current = lvl;
    else break;
  }
  return current;
};

export const getNextLevel = (xp: number) => {
  const current = getLevelForXP(xp);
  const idx = XP_LEVELS.findIndex(l => l.level === current.level);
  return XP_LEVELS[idx + 1] || null;
};
