// Philosophical foundations from "Bewusstsein, Struktur und das gelebte Leben"

export const APHORISMS = [
  'Stärke ist die Fähigkeit, unter Druck bewusst zu bleiben. Gewalt ist leicht. Bewusstheit ist selten.',
  'Bedeutung findet sich nicht in Ereignissen, sondern in Aufmerksamkeit.',
  'Veränderung muss nicht erzwungen werden. Sie geschieht natürlich, wenn das Bewusstsein wächst.',
  'Stille beseitigt Ablenkung. In der Stille werden ungelöste Gedanken sichtbar.',
  'Menschen vergleichen sich, wenn ihr Identitätsgefühl unklar ist.',
  'Während das Bewusstsein wächst, verschwindet das Bedürfnis nach Vergleichen.',
  'Zustimmung erscheint wichtig, weil sie Selbstvertrauen ersetzt.',
  'Ein einfaches Leben, vollständig gelebt, hat mehr Bedeutung als ein außerordentliches Leben, das unbewusst gelebt wird.',
  'Wahrheit herausfordert Bindung und fühlt sich schmerzhaft an, weil sie Illusionen auflöst.',
  'Pflege die Form, in der Welt durch dich bewusst wird.',
];

export const FIVE_PRINCIPLES = [
  {
    number: '01',
    title: 'Trägersystem stabilisieren',
    description: 'Schlaf, Bewegung, Licht, Atem, Ernährung, Regeneration sind ontologische Wartung. Wer die Basis zerlegt, beschädigt das Feld, in dem Geist kohärent erscheinen kann.',
    emoji: '🫀',
    dimension: 'Biologie',
  },
  {
    number: '02',
    title: 'Integrität vor Überreizung schützen',
    description: 'Das Ich ist ein Integrationsprozess. Zu viele Reize, Rollen, offene Schleifen zerfasern ihn. Weniger Dauerlärm, mehr klare Grenzen.',
    emoji: '🧠',
    dimension: 'Kognition',
  },
  {
    number: '03',
    title: 'Bedeutungsvolle Resonanz pflegen',
    description: 'Bewusstsein wird tiefer, wenn es in tragfähiger Beziehung steht. Co-Regulation ist neurobiologische Notwendigkeit. Echte Gespräche, Nähe, Verstandenwerden.',
    emoji: '🤝',
    dimension: 'Sozial',
  },
  {
    number: '04',
    title: 'Struktur bewusst führen',
    description: 'Du wirst nicht nur von Gedanken geformt, sondern von Wiederholungen. Gewohnheiten formen epigenetische Muster. Kleine Rituale, saubere Entscheidungen.',
    emoji: '🔄',
    dimension: 'Kompetenz',
  },
  {
    number: '05',
    title: 'Kohärente Spur leben',
    description: 'Wenn die Person endlich ist, aber Wirkung bleibt, wird Ethik klar. Wie spreche ich? Was baue ich? Wen stärke ich? Was hinterlasse ich in anderen Nervensystemen?',
    emoji: '🌟',
    dimension: 'Bedeutung',
  },
];

export const MINI_SETUPS = [
  {
    id: 'm01',
    number: '01',
    title: 'Schwellen-Puffer',
    description: '5 Minuten vor der Haustür innehalten. Dreimal tief ausatmen. Gedanklich die Arbeitstür schließen.',
    time: '5 Min',
    emoji: '🚪',
    principle: 'Trägersystem',
  },
  {
    id: 'm02',
    number: '02',
    title: 'Ersten 30 Minuten',
    description: 'Smartphone nachts außerhalb des Schlafzimmers. Keine Screens in den ersten 30 Minuten des Tages.',
    time: '30 Min',
    emoji: '🌅',
    principle: 'Integrität',
  },
  {
    id: 'm03',
    number: '03',
    title: 'Gedanken-Parkplatz',
    description: 'Abends alle offenen To-Dos auf ein Blatt schreiben, das am Arbeitsplatz bleibt.',
    time: '5 Min',
    emoji: '📋',
    principle: 'Trägersystem',
  },
  {
    id: 'm04',
    number: '04',
    title: '1-Tab-Regel',
    description: 'Alle Tabs schließen. Ein Fenster für die aktuelle Aufgabe. 45 Minuten.',
    time: '45 Min',
    emoji: '🎯',
    principle: 'Integrität',
  },
  {
    id: 'm05',
    number: '05',
    title: 'Leises Wochenende',
    description: 'Einen halben Tag nichts planen. Keine Treffen. Im Moment entscheiden. DMN-Training.',
    time: '½ Tag',
    emoji: '☁️',
    principle: 'Trägersystem',
  },
  {
    id: 'm06',
    number: '06',
    title: 'Reduzierte Reibung',
    description: 'Kleidung abends bereitlegen. Frühstück standardisieren. Decision Fatigue reduzieren.',
    time: '3 Min',
    emoji: '⚡',
    principle: 'Struktur',
  },
  {
    id: 'm07',
    number: '07',
    title: 'Physiologischer Reset',
    description: 'Eiskaltes Wasser über die Handgelenke, zweimal langsam ausatmen. Parasympathische Aktivierung in 30 Sekunden.',
    time: '30 Sek',
    emoji: '💧',
    principle: 'Trägersystem',
  },
  {
    id: 'm08',
    number: '08',
    title: 'Graustufen-Modus',
    description: 'Smartphone auf Graustufen umstellen. Entfernt den primären Dopamin-Trigger.',
    time: '1 Min',
    emoji: '📱',
    principle: 'Integrität',
  },
  {
    id: 'm09',
    number: '09',
    title: 'Low-Light-Abend',
    description: '90 Minuten vor dem Schlafen alle Deckenlampen aus, nur warme Lichtquellen.',
    time: '90 Min',
    emoji: '🕯️',
    principle: 'Trägersystem',
  },
  {
    id: 'm10',
    number: '10',
    title: '+1-Regel',
    description: 'Beim Verlassen eines Raums einen Gegenstand mitnehmen, der nicht dort hingehört.',
    time: '10 Sek',
    emoji: '🏠',
    principle: 'Struktur',
  },
  {
    id: 'm11',
    number: '11',
    title: 'Weiter Blick',
    description: 'Alle 60 Minuten 2 Minuten aus dem Fenster auf einen weit entfernten Punkt schauen.',
    time: '2 Min',
    emoji: '👁️',
    principle: 'Trägersystem',
  },
  {
    id: 'm12',
    number: '12',
    title: 'Physischer Anker',
    description: 'Aufrecht sitzen, Füße spüren, dreimal in den Bauch atmen. Somatisches Grounding.',
    time: '1 Min',
    emoji: '⚓',
    principle: 'Trägersystem',
  },
  {
    id: 'm13',
    number: '13',
    title: '24-Stunden-Regel',
    description: 'Auf Anfragen immer: „Ich prüfe das kurz und melde mich morgen." Trennt sozialen Druck von rationaler Entscheidung.',
    time: '10 Sek',
    emoji: '⏰',
    principle: 'Integrität',
  },
  {
    id: 'm14',
    number: '14',
    title: 'Erster Sieg',
    description: 'Die wichtigste Aufgabe des Tages in den ersten 60 Arbeitsminuten erledigen — vor dem Postfach.',
    time: '60 Min',
    emoji: '🏆',
    principle: 'Struktur',
  },
  {
    id: 'm15',
    number: '15',
    title: 'Klarer Cut',
    description: 'Laptop zuklappen, Schreibtisch leerräumen, Rechner verstauen. Das physische Ritual des Tagesendes.',
    time: '5 Min',
    emoji: '🌙',
    principle: 'Trägersystem',
  },
];

export const CORE_INSIGHT = 'Du bist das Ergebnis von 13,8 Milliarden Jahren kosmischer Selbstorganisation. Dein Bewusstsein ist kein Unfall — sondern die Innenseite hochgradig organisierter Materie.';

export const TIER_LOGIC = [
  { tier: 0, name: 'Biologie', note: 'Kein höheres Tier ist tragfähig ohne stabile biologische Basis.' },
  { tier: 1, name: 'Emotion', note: 'Ohne emotionale Regulation sind kognitive Leistungen eingeschränkt.' },
  { tier: 2, name: 'Sozial', note: 'Soziale Verbindung ist keine Ergänzung — sie ist biologische Notwendigkeit.' },
  { tier: 3, name: 'Kognition', note: 'Nur wirksam, wenn Basis und Regulation stabil sind.' },
  { tier: 4, name: 'Kompetenz', note: 'Fähigkeiten entstehen durch bewusste Wiederholung.' },
  { tier: 5, name: 'Bedeutung', note: 'Die Spitze der Pyramide, die nur trägt wenn die unteren Ebenen stabil sind.' },
];
